package org.kotlintor.config

/**
 * Additional client / scheduler / dormant / testing options (C Tor or_options_t lite).
 * Inventory: selected L4 or_options rows elevated D0 to D2 when typed here.
 */
data class ClientRuntimeOptions(
    val allDirActionsPrivate: Boolean = false,
    val alwaysCongestionControl: Boolean = false,
    val circuitsAvailableTimeoutSec: Long = 30 * 60,
    val clientBootstrapConsensusAuthorityDownloadInitialDelay: Int = 0,
    val clientBootstrapConsensusAuthorityOnlyDownloadInitialDelay: Int = 0,
    val clientBootstrapConsensusFallbackDownloadInitialDelay: Int = 0,
    val clientBootstrapConsensusMaxInProgressTries: Int = 3,
    val compiledProofOfWorkHash: Int = 0, // AUTOBOOL-ish: 0=auto
    val confluxEnabled: Boolean = true,
    val confluxClientUx: Int = 0,
    val dirCache: Boolean = true,
    val disableOosCheck: Boolean = false,
    val disablePredictedCircuits: Boolean = false,
    val disableSignalHandlers: Boolean = false,
    val dormantCanceledByStartup: Boolean = false,
    val dormantClientTimeoutSec: Long = 24 * 3600,
    val dormantOnFirstStartup: Boolean = false,
    val dormantTimeoutDisabledByIdleStreams: Boolean = true,
    val dormantTimeoutEnabled: Boolean = true,
    val extendByEd25519Id: Boolean = true,
    val geoIpExcludeUnknown: Boolean = false,
    val httpProxy: String? = null,
    val httpsProxy: String? = null,
    val socks4Proxy: String? = null,
    val socks5Proxy: String? = null,
    val tcpProxy: String? = null,
    val tcpProxyProtocol: String = "haproxy",
    val kistSchedRunIntervalMs: Int = 0, // 0 = auto
    val kistSockBufSizeFactor: Double = 1.0,
    val leaveStreamsUnattached: Boolean = false,
    val manualOnionKeyRotation: Boolean = false,
    val maxHsDirCacheBytes: Long = 0,
    val maxUnparseableDescSizeToLog: Long = 10 * 1024 * 1024,
    val pathsNeededToBuildCircuits: Double = 0.6,
    val reconfigDropsBridgeDescs: Boolean = false,
    val reevaluateExitPolicy: Boolean = false,
    val reloadTorrcOnSighup: Boolean = true,
    val rephistTrackTimeSec: Long = 24 * 3600,
    val sslKeyLifetimeDays: Int = 60,
    val sbwsExit: Boolean = false,
    val tokenBucketRefillIntervalMs: Int = 100,
    val trackHostExitsExpireSec: Long = 1800,
    val truncateLogFile: Boolean = false,
    val unixSocksGroupWritable: Boolean = false,
    val useGuardFraction: Boolean = false,
    val v3AuthVotingIntervalSec: Int = 300,
    val v3AuthVoteDelaySec: Int = 20,
    val v3AuthDistDelaySec: Int = 20,
    val v3AuthNIntervalsValid: Int = 3,
    val v3AuthUseLegacyKey: Boolean = false,
    val testingAuthKeyLifetime: String? = null,
    val testingAuthKeySlop: String? = null,
    val testingBridgeBootstrapDownloadInitialDelay: Int = 0,
    val testingBridgeDownloadInitialDelay: Int = 0,
    val testingClientConsensusDownloadInitialDelay: Int = 0,
    val testingClientDownloadInitialDelay: Int = 0,
    val testingClientMaxIntervalWithoutRequest: Int = 0,
    val testingDirConnectionMaxStall: Int = 0,
    val testingEnableCellStatsEvent: Boolean = false,
    val testingEnableConnBwEvent: Boolean = false,
    val testingLinkCertLifetime: String? = null,
    val testingLinkKeySlop: String? = null,
    val testingMinTimeToReportBandwidth: Int = 0,
    val testingServerConsensusDownloadInitialDelay: Int = 0,
    val testingServerDownloadInitialDelay: Int = 0,
    val testingSigningKeySlop: String? = null,
    val testingV3AuthInitialDistDelay: Int = 0,
    val testingV3AuthInitialVoteDelay: Int = 0,
    val testingV3AuthInitialVotingInterval: Int = 0,
    val testingV3AuthVotingStartOffset: Int = 0,
    val usingTestNetworkDefaults: Boolean = false,
    val allFamilyIdsExpected: Boolean = false,
)
